spring:
  application:
    name: OnlineStore
  datasource:
    url: jdbc:mysql://localhost:3306/onlinestore
    username: root
    password: root
  driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
